### PR TITLE
fix CMakeLists.txt: install all headers from the include dir

### PR DESCRIPTION
**Pull request by rautyrauty**
All of them may be required.

### CODE REVIEW

**Comment by rautyrauty** [comment]
```
`-- usr
    |-- include
    |   |-- frei0r
    |   |   |-- blur.h
    |   |   |-- cairo.h
    |   |   |-- cfc.h
    |   |   |-- colorspace.h
    |   |   `-- math.h
    |   |-- frei0r.h
    |   `-- frei0r.hpp
```

**Comment by rautyrauty** [comment]
@jaromil review please

**Comment by rautyrauty** [comment]
@jaromil run the test again

**Comment by rautyrauty** [comment]
@jaromil one more time, please

**Comment by rautyrauty** [comment]
@jaromil review please

**Review by jaromil — APPROVED** [review]
pretty good improvement to standardization and portability, also makes plugin header inclusion more readable by easily distinguishing between frei0r ones and external. Will watch closely next days if something breaks downhill..

**Pull request merged**
