### PR TITLE
fix MSVC compilation

### PR DESCRIPTION
**Pull request by eszlari**
The following filters needed to be disabled because of
Variable Length Arrays (VLA), but are enabled when
compiling with clang-cl:

* curves
* d90stairsteppingfix
* dither

### CODE REVIEW

**Comment by ddennedy** [comment]
This looks good to me, but I have not tested it myself. I trust this contributor as he is helping MLT and Shotcut convert to CMake and maintains many Flatpaks for many projects.

**Comment by eszlari** [comment]
btw: My intention is to add frei0r to https://github.com/microsoft/vcpkg.

**Comment by jaromil** [comment]
@eszlari can you help me understand how to best resolve this conflict?
image

also, do you think that the build you are trying to enable can be in some way reproduced by GitHub actions?

**Comment by jaromil** [comment]
conflicts resolved, msvc build goes well

will try to include it into the upcoming release build, see #130

**Pull request merged**
