### PR TITLE
rgbsplit0r : add both positive and negative directions

### PR DESCRIPTION
**Pull request by d-j-a-y**
horizontal : right/left
vertical : up/down

### CODE REVIEW

**Comment by ddennedy** [comment]
This appears to change the meaning of existing values (values save in a script or project file of an editor). I do not know if that can be avoided but at the very least you should increment the plugin version - major version if the interface semantics are broken by new interpretation of value range.

**Comment by d-j-a-y** [comment]
> This appears to change the meaning of existing values ...

yes that's right ... i update my request with new major version.

**Comment by ddennedy** [comment]
@namikiri Can you please review this since it affects the plugin you created?

**Comment by namikiri** [comment]
Unfortunately I can't pull and build the plugin to test it, so I will rely on @d-j-a-y's experience. 
He said that he wanted to make similar one and suggested me to make double-directional version. He did it for me and I accept it, that's a very good improvement. Thank you a lot, @d-j-a-y!

I approve the changes.

**Pull request merged**
